# Generated by Django 5.0.6 on 2024-08-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_users_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.AlterModelTable(
            name='users_profile',
            table='profile_picture',
        ),
    ]
