# Generated by Django 5.0.6 on 2024-08-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_users_options_alter_users_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_profile',
            old_name='file',
            new_name='profile_picture',
        ),
    ]
