# Generated by Django 5.0.6 on 2024-08-22 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_file_users_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='mat_number'),
        ),
    ]
