# Generated by Django 5.0.6 on 2024-08-22 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_users_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='mat_number'),
        ),
    ]
