# Generated by Django 5.0.6 on 2024-08-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_users_date_of_birth_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_expires',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
