# Generated by Django 5.0.6 on 2024-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_users_id_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
