# Generated by Django 5.0.6 on 2024-09-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_users_id_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profile',
            name='profile_picture',
            field=models.FileField(upload_to='media'),
        ),
    ]
