# Generated by Django 5.0.6 on 2024-09-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_users_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profile',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
