# Generated by Django 5.1.1 on 2024-10-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_users_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
